### ISSUE TITLE
Roadmap to the app store release

### ISSUE THREAD

**Issue by twop** [twop/shelv#153]
here are some rough thoughts, that should be converted into tickets

- [ ] finish slash palette work (#148)
	* [x] bug: sometimes scrolling doesn;t work, seems to be a bug in egui itself
	* [x] adjust documentation for ai injection
		* [x] take shortcuts from the command list
		* [x] see if anything is missing (for example lang prop for code block)
	* [ ] (optional) fuzzy search vs explicit `starts_with()`
- [x] Website
        * [x] Marketing copy 
	* [x] dioxus 0.6 is just about to be shipped, makes sense to wait for that
	  * moved to hyped with SSR rendering 
	* [x] figure out how to embed md documentation into the website
	  * not happening 
	* [x] potentially consider Astro for the website
	* [x] Outline the roadmap, with a call to action to join discord and influence the direction
- [x] Monetization
	* [x] Is there a free option? Or free trial?
	* [x] communication with the app store API
- [x] Better tutorial, probably based on the assistant
